feign:
  hystrix:
    enabled: true
  token:
    propagate:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  redis:
    password: 123456
    host: peppa-redis