spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: peppa-demo1
          uri: lb://peppa-demo1
          predicates:
            - Path=/gateway/peppa-demo1/**
          filters:
            - StripPrefix=2
            - JwtFilter
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: peppa-demo2
          uri: lb://peppa-demo2
          predicates:
            - Path=/gateway/peppa-demo2/**
          filters:
            - StripPrefix=2
            - JwtFilter
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'