spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: peppa-demo2
          uri: lb://localhost:8003
          predicates:
            - Path=/peppa-demo2/**
          filters:
            - StripPrefix=1
        - id: peppa-demo1
          uri: lb://localhost:8002
          predicates:
            - Path=/peppa-demo1/**
          filters:
            - StripPrefix=1